version: "3"

services:
  mysql:
    image: mliezun/branchable-mysql
    platform: linux/amd64
    privileged: true
    restart: always
    volumes:
      - dbdata:/app/layers
      - appdata:/app/web/app.db

volumes:
  dbdata:
  appdata:
